spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
