spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

        - id: liquor-service
          uri: lb://liquor-service
          predicates:
            - Path=/liquor/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
server:
  port: 8761
